config/__init__.py
import flask
import platform
import db

database/__init__.py
__author__ = 'david'

main.py
import sys
import os
import argparse

from flask import Flask
from flask_login import LoginManager

import config
import tools
from tools.accounts import public_not_logged_in


sys.path.insert(0, os.path.realpath(__file__))

app = Flask(__name__)
app.config.from_object(config.flask)

args = None

db = tools.db.open_database()

def set_up_db():
    tools.db.refresh_all_scores(db=db)
    app.db = db

def wipe_database():
    db.drop_collection('users')
    db.drop_collection('teams')
    pass

def register_blueprints():
    import views
    to_register = tools.general.get_reg_list([views])
    for module in to_register:
        app.register_blueprint(module.app)

def set_up_login_manager():
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.user_loader(tools.db.load_user)
    login_manager.login_view = 'api_accounts.public_login'
    login_manager.unauthorized_handler(public_not_logged_in)

def handle_args():
    parser = argparse.ArgumentParser(description='Process some integers.')
    parser.add_argument('--debug', dest='debug', action='store_const', const=True, default=False,
                        help='Use Flask debug mode')
    parser.add_argument('--wipe-db', dest='wipe_db', action='store_const', const=True, default=False,
                        help='Wipe database on startup')
    global args
    args = parser.parse_args()

def set_up_jinja():
    app.jinja_env.trim_blocks = True
    app.jinja_env.lstrip_blocks = True

if __name__ == '__main__':
    handle_args()
    if args.wipe_db:
        wipe_database()
    if args.debug:
        app.debug = True
    set_up_db()
    register_blueprints()
    set_up_login_manager()
    set_up_jinja()
    app.run(host='0.0.0.0')

tools/__init__.py
import api
import general
import db
import accounts
import pages

views/__init__.py
from flask import Blueprint

import tools
import api
import redirect
import pages


app = Blueprint('views', __name__)
to_register = tools.general.get_reg_list([api, pages, redirect])

views/pages/__init__.py
from flask import Blueprint

import tools
import login
import scoreboard
import main_page
import register
import problems
import logout
import team


app = Blueprint('pages', __name__)
to_register = tools.general.get_reg_list([login, scoreboard, main_page, register, problems, logout, team])

views/redirect.py
from flask import Blueprint, request, url_for
from flask import redirect as redirect_user


app = Blueprint('redirect', __name__)

@app.route('/redirect', methods=['GET', 'POST'])
def redirect():
    if 'next' in request.args:
        return redirect_user(request.args['next'])
    else:
        return redirect_user(url_for('page_main.page_main'))

templates/competition_inactive.html
{%- extends "frame.html" -%}
{%- block head -%}
    {{ super() }}
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <style>
        div#content {
            /* Background pattern from subtlepatterns.com */
            background-image: url("{{ url_for('static', filename='darth_stripe.png') }}");
            background-repeat: repeat;
            color: #d8d8d8;
            font-family: "Roboto", sans-serif;
            font-weight: 300;
        }
        .bigtext {
            font-size: 2.5em;
            text-align: center;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function() {
            viewportheight = $(window).height();
            navbarheight = $('#navbarplaceholder').height();
            $('#inner_content').height(viewportheight - navbarheight);
            $(window).resize(function() {
                viewportheight = $(window).height();
                $('#inner_content').height(viewportheight - navbarheight);
            });
        });
    </script>
{% endblock %}
{%- block title -%}
{%- if not g.competition_started -%}
    Competition Not Started
{%- elif g.competition_ended -%}
    Competition Ended
{%- else -%}
    Competition Inactive
{% endif %}
{% endblock %}
{% block content %}
    <div id="inner_content" class="bigtext center">
        {%- if not g.competition_started -%}
            Competition has not begun yet!
        {%- elif g.competition_ended -%}
            Competition ended!
        {%- else -%}
            Competition inactive!
        {% endif %}
    </div>
{% endblock %}

templates/frame.html
<!DOCTYPE html>
<html>
<head lang="en">
    {% block head %}
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style.css') }}">
    <link href='http://fonts.googleapis.com/css?family=Roboto+Condensed' rel='stylesheet' type='text/css'>
    <title>{{ g.ctf_name }} - {% block title %}{% endblock %}</title>
    {% endblock %}
</head>
<body>
    {% block navbar %}
    <div id="navbar" class="navbar">
        <div id="navbarlist">
            <ul id="navbarlist_left" class="navbar inline">
                <li class="navbar"><a class="navbar {% if g.current_page == 'main' %}selected{% endif %}" href="{%- if g.current_page != 'main' -%}{{ url_for('page_main.page_main') }}{% else %}#{% endif %}">Home</a></li>
                <li class="navbar"><a class="navbar {% if g.current_page == 'scoreboard' %}selected{% endif %}" href="{%- if g.current_page != 'scoreboard' -%}{{ url_for('page_scoreboard.page_scoreboard') }}{% else %}#{% endif %}">Scoreboard</a></li>
                {% if g.competition_started %}
                {% if g.show_problems_unauthed or g.authed %}
                <li class="navbar"><a class="navbar {% if g.current_page == 'problems' %}selected{% endif %}" href="{%- if g.current_page != 'problems' -%}{{ url_for('page_problems.page_problems') }}{% else %}#{% endif %}">Problems</a></li>
                {% endif %}
                {% endif %}
            </ul>
            <ul id="navbarlist_right" class="navbar inline right">
                {% if g.authed %}
                <li class="navbar"><a class="navbar {% if g.current_page == 'logout' %}selected{% endif %}" href="{%- if g.current_page != 'logout' -%}{{ url_for('page_logout.page_logout') }}{% else %}#{% endif %}">Logout</a></li>
                {% else %}
                <li class="navbar"><a class="navbar {% if g.current_page == 'register' %}selected{% endif %}" href="{%- if g.current_page != 'register' -%}{{ url_for('page_register.page_register') }}{% else %}#{% endif %}">Register</a></li>
                <li class="navbar"><a class="navbar {% if g.current_page == 'login' %}selected{% endif %}" href="{%- if g.current_page != 'login' -%}{{ url_for('page_login.page_login') }}{% else %}#{% endif %}">Login</a></li>
                {% endif %}
            </ul>
        </div>
	</div>
    <div id="navbarplaceholder" class="navbarplaceholder placeholder"></div>
    {% endblock %}
    <div id="content">
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

templates/login.html
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
    $(document).keyup(function(event){
        if(event.keyCode == 13){
            $('#login_button').click();
        }
    });
    function clear_message(message_box) {
        message_box.html('');
        message_box.css('background-color', '');
    }
    function show_message(message_box, message, color) {
        message_box.html(message);
        message_box.css('background-color', color);
        setTimeout(function() {
            clear_message(message_box)
        }, 1000);
    }
    $('#login_button').click(function () {
        $.post('{{ url_for('api_accounts.public_login') }}', $('#login_form').serialize(), function(data) {
            message_box = $('#message');
            if (data.success) {
                show_message(message_box, data.message, '#0f0');
                $('#login_form').submit();
            } else {
                show_message(message_box, data.message, '#f00');
            }
        });
    });
});
</script>

<div id="message"></div>
<form id="login_form" method="post" action="{{ url_for('redirect.redirect', next=url_for('page_team.page_team')) }}">
    Username or Email: <input type="text" name="identifier" /><br />
    Password: <input type="password" name="password" /><br />
    <button id="login_button" type="button">Log In</button>
</form>

templates/main_page.html
{%- extends "frame.html" -%}
{%- block head -%}
    {{ super() }}
    <script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
    <link href="http://fonts.googleapis.com/css?family=Roboto:300,400" rel="stylesheet" type="text/css">
    <link href="http://fonts.googleapis.com/css?family=Roboto+Slab:300" rel="stylesheet" type="text/css">
    <style>
        div.bigtext {
            font-size: 10em;
            font-family: "Roboto Slab", serif;
            font-weight: 300;
        }
        div.mediumtext {
            font-size: 1em;
            font-family: "Roboto", sans-serif;
            font-weight: 300;
        }
        div#banner {
            /* Background pattern from subtlepatterns.com */
            background-image: url("{{ url_for('static', filename='darth_stripe.png') }}");
            background-repeat: repeat;
        }
        div#ctf_name {
            color: #d8d8d8;
        }
        div#registered_teams {
            color: #ccc;
        }
    </style>
    <script type="text/javascript">
        $(document).ready(function() {
            viewportheight = $(window).height();
            navbarheight = $('#navbarplaceholder').height();
            $('#banner').height(viewportheight - navbarheight);
            $(window).resize(function() {
                viewportheight = $(window).height();
                $('#banner').height(viewportheight - navbarheight);
            });
        });
    </script>
{%- endblock -%}
{%- block title -%}Homepage{% endblock %}
{% block content %}
    <div id="banner" class="center">
        <div id="ctf_name" class="bigtext">{{ g.ctf_name }}</div>
        <div id="registered_teams" class="mediumtext">Registered Teams: {{ team_count }}</div>
    </div>
{% endblock %}

templates/not_in_team.html
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<style>
    div.banner {
        background-color: #f00;
    }
</style>
<script type="text/javascript">
$(document).ready(function () {
    $('#input_join_team').keyup(function(event){
        if(event.keyCode == 13){
            $('#button_join_team').click();
        }
    });
    $('#input_create_team').keyup(function(event){
        if(event.keyCode == 13){
            $('#button_create_team').click();
        }
    });
    function clear_message(message_box) {
        message_box.html('');
        message_box.css('background-color', '');
    }
    function show_message(message_box, message, color) {
        message_box.html(message);
        message_box.css('background-color', color);
        setTimeout(function() {
            clear_message(message_box)
        }, 1000);
    }
    $('#button_join_team').click(function () {
        $.post('{{ url_for('api_accounts.public_join_team') }}', {'name': $('#input_join_team').val()}, function(data) {
            message_box = $('#message');
            if (data.success) {
                show_message(message_box, data.message, '#0f0');
                location.reload(true);
            } else {
                show_message(message_box, data.message, '#f00');
            }
        });
    });
    $('#button_create_team').click(function () {
        $.post('{{ url_for('api_accounts.public_create_team') }}', {'name': $('#input_create_team').val()}, function(data) {
            message_box = $('#message');
            if (data.success) {
                show_message(message_box, data.message, '#0f0');
                location.reload(true);
            } else {
                show_message(message_box, data.message, '#f00');
            }
        });
    });
});
</script>
<div id='join_create_team'>
<div class='banner'>You are not in a team!</div>
<div id='message'></div>
<input id='input_join_team' type='text' /><button id='button_join_team' type='button'>Join</button><br />
<input id='input_create_team' type='text' /><button id='button_create_team' type='button'>Create</button><br />
</div>

templates/problems.html
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function() {
    $('.flag_input').keyup(function(event){
        if(event.keyCode == 13){
            $(this).siblings('.submit_flag_button').click();
        }
    });
    function clear_message(message_box) {
        message_box.html('');
        message_box.css('background-color', '');
    }
    function show_message(message_box, message, color) {
        message_box.html(message);
        message_box.css('background-color', color);
        setTimeout(function() {
            clear_message(message_box)
        }, 1000);
    }
    $('.submit_flag_button').click(function() {
        var button = $(this);
        var flag_input = $(this).siblings('.flag_input')
        if (flag_input.val() === '') {
            return;
        }
        $.post('{{ url_for('api_problems.public_submit_solution') }}', {
            'problem_id': $(this).siblings('.problem_id').html(),
            'flag': flag_input.val()
        }, function(data) {
            flag_input.val('');
            message_box = button.siblings('.message');
            if (!data.success) {
                show_message(message_box, data.message, '#f00');
            } else {
                if (data.data.points_awarded > 0) {
                    show_message(message_box, data.data.message, '#0f0');
                } else {
                    show_message(message_box, data.data.message, '#f00');
                }
            }
        });
    });
});
</script>
<style>
    div.banner {
        background-color: #f00;
    }
</style>
{%- if g.competition_ended -%}
<div class="banner">
    Competition ended!
</div>
{%- endif -%}
{%- if not user_authenticated -%}
<div class="banner">
    Log in to submit flags!
</div>
{%- elif not user_in_team -%}
<div class="banner">
    Join a team to submit flags!
</div>
{%- endif -%}
{%- for problem in problems['data'] -%}
<div class='problem'>
    <div class='problem_id' style='display: none'>{{ problem['id'] }}</div>
    <div class='message'></div>
    {{ problem['name'] }}<br />
    {%- if use_hints -%}
    {{ problem['value'] }} points<br />
    {% endif %}
    {{ problem['statement'] }}<br />
    Hint: {{ problem['hint'] }}<br />
    {%- if user_in_team and g.competition_active -%}
    <input class='flag_input' type='text' />
    <button class="submit_flag_button" type="button">Submit</button>
    {% endif %}
</div>
{% endfor %}

templates/register.html
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<script type="text/javascript">
$(document).ready(function () {
    $(document).keyup(function(event){
        if(event.keyCode == 13){
            $('#register_button').click();
        }
    });
    function clear_message(message_box) {
        message_box.html('');
        message_box.css('background-color', '');
    }
    function show_message(message_box, message, color) {
        message_box.html(message);
        message_box.css('background-color', color);
        setTimeout(function() {
            clear_message(message_box)
        }, 1000);
    }
    $('#register_button').click(function () {
        $.post('{{ url_for('api_accounts.public_register') }}', $('#register_form').serialize(), function(data) {
            message_box = $('#message');
            if (data.success) {
                show_message(message_box, data.message, '#0f0');
                $('#register_form').submit();
            } else {
                show_message(message_box, data.message, '#f00');
            }
        });
    });
});
</script>

<div id="message"></div>
<form id="register_form" method="post" action="{{ url_for('redirect.redirect', next=url_for('page_login.page_login')) }}">
    Type: <input type="radio" name="type" value="student"/> Student<br />
    Email: <input type="text" name="email" /><br />
    Name: <input type="text" name="name" /><br />
    Username: <input type="text" name="username" /><br />
    Password: <input type="password" name="password" /><br />
    <button id="register_button" type="button">Register</button>
</form>

templates/scoreboard.html
<table style="width: 200px">
    {% for team in teams %}
    <tr>
        <td>{{ team['name'] }}</td>
        <td>{{ team['members'] }}</td>
        <td>{{ team['score'] }}</td>
    </tr>
    {% endfor %}
</table>

templates/team.html
<script src="//code.jquery.com/jquery-1.11.2.min.js"></script>
<style>
    div.banner {
        background-color: #f00;
    }
</style>
You're in a team!